project:
  type: website

website:
  title: "Orlando Olaya Bucaro"
  navbar:
    left:
      - href: index.qmd
        text: Home 
      - publications.qmd
      - about.qmd
     

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
execute:
  freeze: auto



